checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: '7.2'
    tests:
        override:
            -
                command: 'php -d phar.readonly=0 ./vendor/bin/phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
