name: Static Analysis

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest

    name: PHPStan

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: 7.3
        extensions: zip
        tools: composer
        coverage: none

    - name: Install PHP dependencies
      uses: ramsey/composer-install@994bb194a4fefcf39449ccf0f7766a4318f1ac76 # v1
      with:
        dependency-versions: highest
        composer-options: "--prefer-dist"

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi