name: Tests

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2']
        dependency-version: [lowest, highest]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup PHP
      uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
      with:
        php-version: ${{ matrix.php }}
        extensions: zip
        tools: composer
        coverage: none

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP dependencies
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v2
      with:
        dependency-versions: ${{ matrix.dependency-version }}
        composer-options: "--prefer-dist"

    - name: Unit Tests
      run: vendor/bin/pest --colors=always