name: Tests

on: ['push', 'pull_request']

permissions:
  contents: read

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.2', '8.3', '8.4', '8.5']
        dependency-version: [lowest, highest]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: ${{ matrix.php }}
        extensions: zip
        tools: composer:v2
        coverage: none

    - name: Setup Problem Matches
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install PHP dependencies
      run: composer update --prefer-dist --no-interaction ${{ matrix.dependency-version == 'lowest' && '--prefer-lowest' || '' }}

    - name: Run Tests
      run: vendor/bin/pest --display-deprecation ${{ matrix.dependency-version == 'highest' && '--fail-on-deprecation' || '' }}
